apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: aqua-web-pvc
  namespace: aqua
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: ocs-storagecluster-cephfs
status: {}